services:
  - name: client
    type: web
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: NODE_ENV
        value: production

  - name: server
    type: web
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: mongodb+srv://jammivyshnavi:1234@cluster0.bcnui.mongodb.net/
